language: python
python:
  - "3.7"
script:
 - python -m unittest discover
 - python -m unittest mars_rover_tests/mars_rover_tests.py 
install:      
      - pip install coverage
      - pip install parameterize
after_success: coverage report
notifications:
  email: 
    - matiastripode@gmail.com
